import { Post } from '../interfaces/post.interface';

export const Posts: Post[] =
[
{ id: 1, 
titulo: 'El cuento de la criada', 
texto: 'Amparándose en la coartada del terrorismo, unos políticos teócratas se hacen con el poder y, como primera medida, suprimen la libertad de prensa y los derechos de las mujeres. Esta trama, inquietante y oscura, que bien podría encontrarse en cualquier obra actual, pertenece en realidad a esta novela escrita por Margaret Atwood a principios de los ochenta, en la que la afamada autora canadiense anticipó con llamativa premonición una amenaza latente en el mundo de hoy.',
autor: 'Margaret Atwood',
imagen: 'https://m.media-amazon.com/images/I/71YkUT7YS9L.jpg',
fecha: '04/03/2021',
categoria: 'Ficción Social',
},
{ id: 2, 
titulo: 'Babel', 
texto: '1828. El Instituto Real de Traducción de Oxford, también conocido como Babel, es la institución mágica más importante del mundo. La magia con plata capaz de revelar significados ocultos perdidos en la traducción que allí se practica le ha otorgado al Imperio británico un poder sin parangón. Para Robin, un huérfano cantonés que ha terminado siendo alumno en Babel, se ha dado cuenta de que servir a Babel significa traicionar a su país de origen. Y, a medida que sus estudios progresan, se ve atrapado entre babel y la misteriosa Sociedad de Hermes, una organización dedicada a impedir la expansión imperial. Cuando Gran Bretaña trate de iniciar una injusta guerra con China motivada por el opio y a plata, Robin deberá decidir si la única forma de lograr un cambio real es la violencia.',
autor: 'RF Kuang',
imagen: 'https://m.media-amazon.com/images/I/814Ty7sxKNL.jpg', 
fecha: '28/11/2022',
categoria: 'Fantasía',
},
{ id: 3, 
titulo: 'La estirpe de Lilith', 
texto: 'Treinta años después de su primera publicación en castellano, La estirpe de Lilith, título que reúne la Trilogía Xenogénesis en un solo volumen, vuelve a las librerías dispuesta a reivindicar a Octavia E. Butler como la gran pionera que deslumbró en ciencia ficción siendo una mujer negra. Hoy se la considera la primera escritora afroamericana de género en incorporarse al canon de la literatura norteamericana.',
autor: 'Octavia Butler',
imagen: 'https://m.media-amazon.com/images/I/818H1NoSaTL.jpg', 
fecha: '08/04/2021',
categoria: 'Ciencia ficción',
},
{ id: 4, 
titulo: 'El nombre del mundo es Bosque', 
texto: 'Dentro de la gran tradición literaria de las utopías y antiutopías que se inicia en el siglo XVII, El nombre del mundo es Bosque muestra una vez más la claridad y el poder de la visión «ecológica» de Ursula K. Le Guin: un universo dinámico y en equilibrio que se mantiene en el tiempo de acuerdo con leyes propias que no admiten la intromisión del hombre.',
autor: 'Úrsula K LeGuin',
imagen: 'https://m.media-amazon.com/images/I/81CTJ+LdY8L.jpg', 
fecha: '28/04/2021',
categoria: 'Fantasía',
},
{ id: 5, 
titulo: 'El hombre hembra', 
texto: 'El hombre hembra, una de las obras más influyentes de la literatura feminista, fue escrita en 1970 y, lejos de perder vigencia, sigue siendo absolutamente pertinente en la actualidad. Con ella, la escritora Joanna Russ reivindicaba que la ciencia ficción ya estaba lista para proporcionar nuevos mitos literarios en un género dominado por hombres, y que podía ayudar a liberar a las mujeres.',
autor: 'Joanna Russ',
imagen: 'https://m.media-amazon.com/images/I/81mr65SQ1rL.jpg', 
fecha: '11/02/2021',
categoria: 'Ficción Social',
},
{ id: 6, 
titulo: 'Frankenstein o El moderno Prometeo', 
texto: 'Durante el lluvioso verano de 1816, cuatro de los escritores ingleses más talentosos de su tiempo se dieron cita en Villa Diodati. La mansión a orillas del lago Ginebra fue el escenario en que Lord Byron, John Polidori, Percy Bysshe Shelley y Mary Shelley se retaron a escribir una historia de terror. Aquel juego llevó a la autora londinense a crear Frankenstein, una de las grandes cimas del horror gótico y una brillante reflexión sobre la ética científica. La novela narra el intento de un joven estudiante de medicina de crear vida artificial y las terribles consecuencias de su experimento.',
autor: 'Mary Shelley',
imagen: 'https://m.media-amazon.com/images/I/71ldz8QXgkL.jpg', 
fecha: '24/11/2017',
categoria: 'Terror',
},
{ id: 7, 
titulo: 'Siempre hemos vivido en el castillo', 
texto: '«Me llamo Mary Katherine Blackwood. Tengo dieciocho años y vivo con mi hermana Constance. A menudo pienso que con un poco de suerte podría haber sido una mujer lobo, porque mis dedos medio y anular son igual de largos, pero he tenido que contentarme con lo que soy. No me gusta lavarme, ni los perros, ni el ruido. Me gusta mi hermana Constance, y Ricardo Plantagenet, y la Amanita phalloides, la oronja mortal. El resto de mi familia ha muerto.» Con estas palabras se presenta Merricat, la protagonista de Siempre hemos vivido en el castillo, que lleva una vida solitaria en una gran casa apartada del pueblo. Allí pasa las horas recluida con su bella hermana mayor y su anciano tío Julian, que va en silla de ruedas y escribe y reescribe sus memorias. La buena cocina, la jardinería y el gato Jonas concentran la atención de las jóvenes. En el hogar de los Blackwood los días discurrirían apacibles si no fuera porque algo ocurrió, allí mismo, en el comedor, seis años atrás.',
autor: 'Shirley Jackson',
imagen: 'https://m.media-amazon.com/images/I/617Wyw2zo4L.jpg', 
fecha: '11/01/2017',
categoria: 'Terror',
},
{ id: 8, 
titulo: 'Rebeca', 
texto: 'Nadie que conozca la película basada en esta novela podrá olvidar la voz en off que recita la frase inicial de la obra más lograda de Daphne du Maurier: Rebeca. Así comienzan los recuerdos de la segunda señora De Winter, que la transportan de nuevo a la aislada y gris mansión situada en la húmeda y ventosa costa de Cornualles. Con un marido al que apenas conoce, la joven esposa llega a este inmenso predio para ser inexorablemente ahogada por la fantasmal presencia de la primera señora De Winter, la hermosa Rebeca, muerta pero nunca olvidada. Su habitación permanece intacta, sus vestidos listos para ser lucidos y su sirvienta, la siniestra señora Danvers, aún le profesa una devoción malsana.',
autor: 'Daphne Du Maurier',
imagen: 'https://m.media-amazon.com/images/I/91V8-vR2MYL.jpg', 
fecha: '26/03/2006',
categoria: 'Thriller',
},
{ id: 9, 
titulo: 'El secreto', 
texto: 'El secreto, primera novela de la gran Donna Tartt, se cuenta entre las mejores obras del siglo XX. Uno de esos libros nacidos para ser clásicos instantáneos. Una lectura perfecta para estar en el sofá, tapado, con la única necesidad de devorar sus páginas (advertencia: tiene un alto componente adictivo, que su longitud no cause rechazo a los curiosos). [...] Durante sus páginas se puede disfrutar con todo: el misterio, el lujo, amores no correspondidos... El propio college semeja un elemento vivo más. Cualquier enamoradode la estética dark academia (hola, Miércoles Adams) encontrará aquí el santo grial».',
autor: 'Donna Tartt',
imagen: 'https://m.media-amazon.com/images/I/81d0taMyb2L.jpg', 
fecha: '13/03/2014',
categoria: 'Thriller',
},
{ id: 10, 
titulo: 'El largo viaje a un pequeño planeta iracundo', 
texto: 'Un profundo road trip literario de personajes complejos y tridimensionales con los que cualquier lector se podrá identificar. Ganadora del Prix Julia Verlanger en 2017. Rosemary Harper se une a la tripulación de la Peregrina, una vieja nave tuneladora, sin saber muy bien qué esperar de su primer trabajo. Aunque la nave ha visto tiempos mejores, le ofrece un pequeño lugar al que llamar hogar durante un tiempo, algo de aventura en los confines más alejados de la galaxia y, lo que es más importante para ella, la oportunidad de dejar atrás su pasado.',
autor: 'Becky Chambers',
imagen: 'https://m.media-amazon.com/images/I/81u1P-Me-GL.jpg', 
fecha: '29/01/2018',
categoria: 'Ciencia ficción',
},
]
